# Tokyo Night Day
# By: Folke Lemaitre
# Official Tokyo Night theme - Day variant (Light)
#
# Source: https://github.com/folke/tokyonight.nvim
# Extracted from: extras/lua/tokyonight_day.lua

[theme]
name = "Tokyo Night Day"
author = "folke"
variant = "light"

[palette]
# Background shades
bg = "#e1e2e7"
bg_dark = "#d0d5e3"
bg_float = "#d0d5e3"
bg_highlight = "#c4c8da"
bg_popup = "#d0d5e3"
bg_search = "#7890dd"
bg_sidebar = "#d0d5e3"
bg_statusline = "#d0d5e3"
bg_visual = "#b7c1e3"
black = "#b4b5b9"

# Foreground shades
fg = "#3760bf"
fg_dark = "#6172b0"
fg_float = "#3760bf"
fg_gutter = "#a8aecb"
fg_sidebar = "#6172b0"

# Core colors
blue = "#2e7de9"
blue0 = "#7890dd"
blue1 = "#188092"
blue2 = "#07879d"
blue5 = "#006a83"
blue6 = "#2e5857"
blue7 = "#92a6d5"
cyan = "#007197"
green = "#587539"
green1 = "#387068"
green2 = "#38919f"
magenta = "#9854f1"
magenta2 = "#d20065"
orange = "#b15c00"
purple = "#7847bd"
red = "#f52a65"
red1 = "#c64343"
teal = "#118c74"
yellow = "#8c6c3e"

# UI colors
comment = "#848cb5"
dark3 = "#8990b3"
dark5 = "#68709a"
border = "#b4b5b9"
border_highlight = "#4094a3"
terminal_black = "#a1a6c5"
hint = "#118c74"
info = "#07879d"
warning = "#8c6c3e"
error = "#c64343"

[syntax]
keyword = "cyan"
control = "purple"
type = "blue1"
operator = "cyan"
boolean = "orange"
function = "blue"
method = "blue"
variable = "fg"
parameter = "yellow"
field = "green1"
property = "green1"
constant = "orange"
string = "green"
string_escape = "magenta"
number = "orange"
char = "green"
comment = "comment"
comment_doc = "dark5"
todo = "blue"
error_token = "error"
warning_token = "warning"
deprecated = "dark3"
macro = "purple"
label = "blue"

[ui]
background = "bg"
foreground = "fg"
background_alt = "bg_dark"
border = "border"
border_active = "border_highlight"
vert_split = "bg_highlight"
line_number = "fg_gutter"
line_number_current = "blue"
cursor = "fg"
cursor_line = "bg_highlight"
cursor_line_number = "blue"
selection = "bg_visual"
visual = "bg_visual"
search = "bg_search"
search_match = "orange"
status_line = "fg_dark"
status_line_inactive = "fg_gutter"
tab_active = "blue"
tab_inactive = "fg_gutter"
popup_bg = "bg_popup"
popup_border = "border_highlight"
float_bg = "bg_float"
float_border = "border_highlight"
fuzzy_match = "cyan"
fuzzy_file = "fg"
fuzzy_dir = "blue"
fuzzy_border = "border_highlight"

[git]
added = "#4197a4"
modified = "#506d9c"
removed = "red"
deleted = "red"
conflict = "orange"
diff_add_bg = "#b7ced5"
diff_change_bg = "#d5d9e4"
diff_delete_bg = "#dababe"

[diagnostic]
error = "error"
warning = "warning"
info = "info"
hint = "hint"

[terminal]
black = "#b4b5b9"
red = "#f52a65"
green = "#587539"
yellow = "#8c6c3e"
blue = "#2e7de9"
magenta = "#9854f1"
cyan = "#007197"
white = "#6172b0"
bright_black = "#a1a6c5"
bright_red = "#ff4774"
bright_green = "#5c8524"
bright_yellow = "#a27629"
bright_blue = "#358aff"
bright_magenta = "#a463ff"
bright_cyan = "#007ea8"
bright_white = "#3760bf"
