# Tokyo Night Moon
# By: Folke Lemaitre
# Official Tokyo Night theme - Moon variant
#
# Source: https://github.com/folke/tokyonight.nvim
# Extracted from: extras/lua/tokyonight_moon.lua

[theme]
name = "Tokyo Night Moon"
author = "folke"
variant = "dark"

[palette]
# Background shades
bg = "#222436"
bg_dark = "#1e2030"
bg_float = "#1e2030"
bg_highlight = "#2f334d"
bg_popup = "#1e2030"
bg_search = "#3e68d7"
bg_sidebar = "#1e2030"
bg_statusline = "#1e2030"
bg_visual = "#2d3f76"
black = "#1b1d2b"

# Foreground shades
fg = "#c8d3f5"
fg_dark = "#828bb8"
fg_float = "#c8d3f5"
fg_gutter = "#3b4261"
fg_sidebar = "#828bb8"

# Core colors
blue = "#82aaff"
blue0 = "#3e68d7"
blue1 = "#65bcff"
blue2 = "#0db9d7"
blue5 = "#89ddff"
blue6 = "#b4f9f8"
blue7 = "#394b70"
cyan = "#86e1fc"
green = "#c3e88d"
green1 = "#4fd6be"
green2 = "#41a6b5"
magenta = "#c099ff"
magenta2 = "#ff007c"
orange = "#ff966c"
purple = "#fca7ea"
red = "#ff757f"
red1 = "#c53b53"
teal = "#4fd6be"
yellow = "#ffc777"

# UI colors
comment = "#636da6"
dark3 = "#545c7e"
dark5 = "#737aa2"
border = "#1b1d2b"
border_highlight = "#589ed7"
terminal_black = "#444a73"
hint = "#4fd6be"
info = "#0db9d7"
warning = "#ffc777"
error = "#c53b53"

[syntax]
keyword = "cyan"
control = "purple"
type = "blue1"
operator = "cyan"
boolean = "orange"
function = "blue"
method = "blue"
variable = "fg"
parameter = "yellow"
field = "green1"
property = "green1"
constant = "orange"
string = "green"
string_escape = "magenta"
number = "orange"
char = "green"
comment = "comment"
comment_doc = "dark5"
todo = "blue"
error_token = "error"
warning_token = "warning"
deprecated = "dark3"
macro = "purple"
label = "blue"

[ui]
background = "bg"
foreground = "fg"
background_alt = "bg_dark"
border = "border"
border_active = "border_highlight"
vert_split = "bg_highlight"
line_number = "fg_gutter"
line_number_current = "blue"
cursor = "fg"
cursor_line = "bg_highlight"
cursor_line_number = "blue"
selection = "bg_visual"
visual = "bg_visual"
search = "bg_search"
search_match = "orange"
status_line = "fg_dark"
status_line_inactive = "fg_gutter"
tab_active = "blue"
tab_inactive = "fg_gutter"
popup_bg = "bg_popup"
popup_border = "border_highlight"
float_bg = "bg_float"
float_border = "border_highlight"
fuzzy_match = "cyan"
fuzzy_file = "fg"
fuzzy_dir = "blue"
fuzzy_border = "border_highlight"

[git]
added = "green"
modified = "blue"
removed = "red"
deleted = "red"
conflict = "orange"
diff_add_bg = "#2a4556"
diff_change_bg = "#252a3f"
diff_delete_bg = "#4b2a3d"

[diagnostic]
error = "error"
warning = "warning"
info = "info"
hint = "hint"

[terminal]
black = "#1b1d2b"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffc777"
blue = "#82aaff"
magenta = "#c099ff"
cyan = "#86e1fc"
white = "#828bb8"
bright_black = "#444a73"
bright_red = "#ff8d94"
bright_green = "#c7fb6d"
bright_yellow = "#ffd8ab"
bright_blue = "#9ab8ff"
bright_magenta = "#caabff"
bright_cyan = "#b2ebff"
bright_white = "#c8d3f5"
