# Tokyo Night Night
# By: Folke Lemaitre
# Official Tokyo Night theme - Night variant (Classic)
#
# Source: https://github.com/folke/tokyonight.nvim
# Extracted from: extras/lua/tokyonight_night.lua

[theme]
name = "Tokyo Night Night"
author = "folke"
variant = "dark"

[palette]
# Background shades
bg = "#1a1b26"
bg_dark = "#16161e"
bg_float = "#16161e"
bg_highlight = "#292e42"
bg_popup = "#16161e"
bg_search = "#3d59a1"
bg_sidebar = "#16161e"
bg_statusline = "#16161e"
bg_visual = "#283457"
black = "#15161e"

# Foreground shades
fg = "#c0caf5"
fg_dark = "#a9b1d6"
fg_float = "#c0caf5"
fg_gutter = "#3b4261"
fg_sidebar = "#a9b1d6"

# Core colors
blue = "#7aa2f7"
blue0 = "#3d59a1"
blue1 = "#2ac3de"
blue2 = "#0db9d7"
blue5 = "#89ddff"
blue6 = "#b4f9f8"
blue7 = "#394b70"
cyan = "#7dcfff"
green = "#9ece6a"
green1 = "#73daca"
green2 = "#41a6b5"
magenta = "#bb9af7"
magenta2 = "#ff007c"
orange = "#ff9e64"
purple = "#9d7cd8"
red = "#f7768e"
red1 = "#db4b4b"
teal = "#1abc9c"
yellow = "#e0af68"

# UI colors
comment = "#565f89"
dark3 = "#545c7e"
dark5 = "#737aa2"
border = "#15161e"
border_highlight = "#27a1b9"
terminal_black = "#414868"
hint = "#1abc9c"
info = "#0db9d7"
warning = "#e0af68"
error = "#db4b4b"

[syntax]
keyword = "cyan"
control = "purple"
type = "blue1"
operator = "cyan"
boolean = "orange"
function = "blue"
method = "blue"
variable = "fg"
parameter = "yellow"
field = "green1"
property = "green1"
constant = "orange"
string = "green"
string_escape = "magenta"
number = "orange"
char = "green"
comment = "comment"
comment_doc = "dark5"
todo = "blue"
error_token = "error"
warning_token = "warning"
deprecated = "dark3"
macro = "purple"
label = "blue"

[ui]
background = "bg"
foreground = "fg"
background_alt = "bg_dark"
border = "border"
border_active = "border_highlight"
vert_split = "bg_highlight"
line_number = "fg_gutter"
line_number_current = "blue"
cursor = "fg"
cursor_line = "bg_highlight"
cursor_line_number = "blue"
selection = "bg_visual"
visual = "bg_visual"
search = "bg_search"
search_match = "orange"
status_line = "fg_dark"
status_line_inactive = "fg_gutter"
tab_active = "blue"
tab_inactive = "fg_gutter"
popup_bg = "bg_popup"
popup_border = "border_highlight"
float_bg = "bg_float"
float_border = "border_highlight"
fuzzy_match = "cyan"
fuzzy_file = "fg"
fuzzy_dir = "blue"
fuzzy_border = "border_highlight"

[git]
added = "#449dab"
modified = "#6183bb"
removed = "red"
deleted = "red"
conflict = "orange"
diff_add_bg = "#243e4a"
diff_change_bg = "#1f2231"
diff_delete_bg = "#4a272f"

[diagnostic]
error = "error"
warning = "warning"
info = "info"
hint = "hint"

[terminal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"
bright_black = "#414868"
bright_red = "#ff899d"
bright_green = "#9fe044"
bright_yellow = "#faba4a"
bright_blue = "#8db0ff"
bright_magenta = "#c7a9ff"
bright_cyan = "#a4daff"
bright_white = "#c0caf5"
